74 notes feature for photoinput and photo components
pnnl/Quality-Install-Tool pull request #253
Opened 2024-12-18 18:26 UTC by lindsayJohnstonPnnl

2024-12-18 22:35 UTC, lindsayJohnstonPnnl commented
![image](https://github.com/user-attachments/assets/48f8886b-dd5e-42dd-94f2-2301257ff040)

2025-01-07 21:13 UTC, sudhacheran requested changes

2025-01-07 21:13 UTC, sudhacheran commented on src/components/photo_input.tsx
> +import TextInput from './text_input'
We could use the TextInputWrapper to directly access the StoreContext and update.

2025-01-07 21:13 UTC, sudhacheran commented on src/components/photo_input.tsx
> +    noteValue: JSONValue | undefined
Using TextInputWrapper, we could avoid updating it separately.

2025-01-07 21:13 UTC, sudhacheran commented on src/components/photo_input_wrapper.tsx
> +                data,
same as above

2025-01-27 18:03 UTC, sudhacheran commented
The changes looks good to me. Thanks!

2025-01-27 18:04 UTC, sudhacheran approved these changes

2025-02-04 19:31 UTC, merged